const defaultProducts = [
  {
    model: "Gorro Neo Gris",
    slug: "gorro-m2-gris-atic",
    sku: "GNGRIS1",
    submodel: "",
    description: "Gorro de invierno 100% algodón. No vas a pasar mas frío.",
    details: { color: "Gris" },
    category: "indumentaria",
    sub_category: "gorros",
    project: "atic",
    images_url: ["atic-gorro-m2-gris.png"],
    orders: [],
    sales_quantity: 0,
    price: 320,
    cost: 180,
    stock: 5,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Gorro Clásico Gris",
    slug: "gorro-m1-gris-atic",
    sku: "GCGRIS1",
    submodel: "",
    description: "Gorro de invierno 100% algodón. No vas a pasar mas frío.",
    details: { color: "Gris" },
    category: "indumentaria",
    sub_category: "gorros",
    project: "atic",
    images_url: ["atic-gorro-m1-gris.png"],
    orders: [],
    sales_quantity: 0,
    price: 320,
    cost: 180,
    stock: 5,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Gorro Clásico Mostaza",
    slug: "gorro-m1-mostaza-atic",
    sku: "GCMOST1",
    submodel: "",
    description: "Gorro de invierno 100% algodón. No vas a pasar mas frío.",
    details: { color: "Mostaza" },
    category: "indumentaria",
    sub_category: "gorros",
    project: "atic",
    images_url: ["atic-gorro-m1-mostaza.png"],
    orders: [],
    sales_quantity: 0,
    price: 320,
    cost: 180,
    stock: 5,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Gorro Clásico Negro",
    slug: "gorro-m1-negro-atic",
    sku: "GCNEGRO1",
    submodel: "",
    description: "Gorro de invierno 100% algodón. No vas a pasar mas frío.",
    details: { color: "Negro" },
    category: "indumentaria",
    sub_category: "gorros",
    project: "atic",
    images_url: ["atic-gorro-m1-negro.png"],
    orders: [],
    sales_quantity: 0,
    price: 320,
    cost: 180,
    stock: 5,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Gorro Clásico Rojo",
    slug: "gorro-m1-rojo-atic",
    sku: "GCROJO1",
    submodel: "",
    description: "Gorro de invierno 100% algodón. No vas a pasar mas frío.",
    details: { color: "Rojo" },
    category: "indumentaria",
    sub_category: "gorros",
    project: "atic",
    images_url: ["atic-gorro-m1-rojo.png"],
    orders: [],
    sales_quantity: 0,
    price: 320,
    cost: 180,
    stock: 5,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Gorro Neo Rojo",
    slug: "gorro-m2-rojo-atic",
    sku: "GNROJO1",
    submodel: "",
    description: "Gorro de invierno 100% algodón. No vas a pasar mas frío.",
    details: { color: "Rojo" },
    category: "indumentaria",
    sub_category: "gorros",
    project: "atic",
    images_url: ["atic-gorro-m2-rojo.png"],
    orders: [],
    sales_quantity: 0,
    price: 320,
    cost: 180,
    stock: 5,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Gorro Clásico Verde",
    slug: "gorro-m1-verde-atic",
    sku: "GCVERDE1",
    submodel: "",
    description: "Gorro de invierno 100% algodón. No vas a pasar mas frío.",
    details: { color: "Verde" },
    category: "indumentaria",
    sub_category: "gorros",
    project: "atic",
    images_url: ["atic-gorro-m1-verde.png"],
    orders: [],
    sales_quantity: 0,
    price: 320,
    cost: 180,
    stock: 5,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Gorro Neo Verde",
    slug: "gorro-m2-verde-atic",
    sku: "GNVERDE1",
    submodel: "",
    description: "Gorro de invierno 100% algodón. No vas a pasar mas frío.",
    details: { color: "Verde" },
    category: "indumentaria",
    sub_category: "gorros",
    project: "atic",
    images_url: ["atic-gorro-m2-verde.png"],
    orders: [],
    sales_quantity: 0,
    price: 320,
    cost: 180,
    stock: 5,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Gorro Clásico Amarillo",
    slug: "gorro-m1-amarillo-atic",
    sku: "GCAMA1",
    submodel: "",
    description: "Gorro de invierno 100% algodón. No vas a pasar mas frío.",
    details: { color: "Amarillo" },
    category: "indumentaria",
    sub_category: "gorros",
    project: "atic",
    images_url: ["atic-gorro-m1-amarillo.png"],
    orders: [],
    sales_quantity: 0,
    price: 320,
    cost: 180,
    stock: 5,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Camiseta Clásica Hand",
    slug: "camiseta-m-hand-negra-atic",
    sku: "CCHANDBLACK1",
    submodel: "",
    description: "",
    details: { color: "Negro" },
    category: "indumentaria",
    sub_category: "camisetas",
    project: "atic",
    images_url: ["atic-camiseta-hand-negra-1.png"],
    orders: [],
    sales_quantity: 0,
    price: 580,
    cost: 320,
    stock: 10,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Camiseta Clásica Snake",
    slug: "camiseta-m-snake-negra-atic",
    sku: "CCSNAKEBLACK1",
    submodel: "",
    description: "",
    details: { color: "Negro" },
    category: "indumentaria",
    sub_category: "camisetas",
    project: "atic",
    images_url: ["atic-camiseta-snake-negra-1.png"],
    orders: [],
    sales_quantity: 0,
    price: 580,
    cost: 320,
    stock: 10,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Camiseta Clásica Skull",
    slug: "camiseta-m-skull-negra-atic",
    sku: "CCSKULLBLACK1",
    submodel: "",
    description: "",
    details: { color: "Negro" },
    category: "indumentaria",
    sub_category: "camisetas",
    project: "atic",
    images_url: ["atic-camiseta-skull-negra-1.png"],
    orders: [],
    sales_quantity: 0,
    price: 580,
    cost: 320,
    stock: 10,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Buzo Clásico Skull",
    slug: "buzo-m-skull-negro-atic",
    sku: "BCSKULLBLACK1",
    submodel: "",
    description: "",
    details: { color: "Negro" },
    category: "indumentaria",
    sub_category: "buzos",
    project: "atic",
    images_url: ["atic-buzo-skull-negro-1.png"],
    orders: [],
    sales_quantity: 0,
    price: 1200,
    cost: 700,
    stock: 5,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Buzo Clásico Hand",
    slug: "buzo-m-hand-negro-atic",
    sku: "BCHANDBLACK1",
    submodel: "",
    description: "",
    details: { color: "Negro" },
    category: "indumentaria",
    sub_category: "buzos",
    project: "atic",
    images_url: ["atic-buzo-hand-negro-1.png"],
    orders: [],
    sales_quantity: 0,
    price: 1200,
    cost: 700,
    stock: 5,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Buzo Clásico Snake",
    slug: "buzo-m-snake-negro-atic",
    sku: "BCSNAKEBLACK1",
    submodel: "",
    description: "",
    details: { color: "Negro" },
    category: "indumentaria",
    sub_category: "buzos",
    project: "atic",
    images_url: ["atic-buzo-snake-negro-1.png"],
    orders: [],
    sales_quantity: 0,
    price: 1200,
    cost: 700,
    stock: 5,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Billetera Automática M.1 Black",
    slug: "billetera-automatica-negra-1",
    sku: "BAUTOBLACK1",
    submodel: "",
    description: "",
    details: { color: "Negro" },
    category: "accesorios",
    sub_category: "billeteras",
    project: "tero_ventas",
    images_url: ["teroventas-billetera-automatica-m1-negra-1.png"],
    orders: [],
    sales_quantity: 0,
    price: 1095,
    cost: 500,
    stock: 3,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Billetera Automática M.1 Grey",
    slug: "billetera-automatica-gris-1",
    sku: "BAUTOGREY1",
    submodel: "",
    description: "",
    details: { color: "Negro" },
    category: "accesorios",
    sub_category: "billeteras",
    project: "tero_ventas",
    images_url: ["teroventas-billetera-automatica-m1-gris-1.png"],
    orders: [],
    sales_quantity: 0,
    price: 1095,
    cost: 500,
    stock: 2,
    projects_provider: [],
    providers: [],
  },
  {
    model: "Billetera Automática M.1 Brown",
    slug: "billetera-automatica-brown-1",
    sku: "BAUTOBROWN1",
    submodel: "",
    description: "",
    details: { color: "Marrón" },
    category: "accesorios",
    sub_category: "billeteras",
    project: "tero_ventas",
    images_url: ["teroventas-billetera-automatica-m1-marron-1.png"],
    orders: [],
    sales_quantity: 0,
    price: 1095,
    cost: 500,
    stock: 2,
    projects_provider: [],
    providers: [],
  },
];

module.exports = defaultProducts;
