const defaultProducts = [
  {
    name: "Gorro Neo Gris",
    slug: "gorro-m2-gris-atic",
    subname: "",
    description: "",
    details: { color: "Gris" },
    subcategories: ["gorros"],
    project: "atic",
    images_url: ["atic-gorro-m2-gris.png"],
    orders: [],
    price: 320,
    cost: 180,
    stock: 5,
    providers: [],
  },
  {
    name: "Gorro Clásic Gris",
    slug: "gorro-m1-gris-atic",
    subname: "",
    description: "",
    details: { color: "Gris" },
    subcategories: ["gorros"],
    project: "atic",
    images_url: ["atic-gorro-m1-gris.png"],
    orders: [],
    price: 320,
    cost: 180,
    stock: 5,
    providers: [],
  },
  {
    name: "Gorro Clásic Mostaza",
    slug: "gorro-m1-mostaza-atic",
    subname: "",
    description: "",
    details: { color: "Mostaza" },
    subcategories: ["gorros"],
    project: "atic",
    images_url: ["atic-gorro-m1-mostaza.png"],
    orders: [],
    price: 320,
    cost: 180,
    stock: 5,
    providers: [],
  },
  {
    name: "Gorro Clásic Negro",
    slug: "gorro-m1-negro-atic",
    subname: "",
    description: "",
    details: { color: "Negro" },
    subcategories: ["gorros"],
    project: "atic",
    images_url: ["atic-gorro-m1-negro.png"],
    orders: [],
    price: 320,
    cost: 180,
    stock: 5,
    providers: [],
  },
  {
    name: "Gorro Clásic Rojo",
    slug: "gorro-m1-rojo-atic",
    subname: "",
    description: "",
    details: { color: "Rojo" },
    subcategories: ["gorros"],
    project: "atic",
    images_url: ["atic-gorro-m1-rojo.png"],
    orders: [],
    price: 320,
    cost: 180,
    stock: 5,
    providers: [],
  },
  {
    name: "Gorro Neo Rojo",
    slug: "gorro-m2-rojo-atic",
    subname: "",
    description: "",
    details: { color: "Rojo" },
    subcategories: ["gorros"],
    project: "atic",
    images_url: ["atic-gorro-m2-rojo.png"],
    orders: [],
    price: 320,
    cost: 180,
    stock: 5,
    providers: [],
  },
  {
    name: "Gorro Clásic Verde",
    slug: "gorro-m1-verde-atic",
    subname: "",
    description: "",
    details: { color: "Verde" },
    subcategories: ["gorros"],
    project: "atic",
    images_url: ["atic-gorro-m1-verde.png"],
    orders: [],
    price: 320,
    cost: 180,
    stock: 5,
    providers: [],
  },
  {
    name: "Gorro Neo Verde",
    slug: "gorro-m2-verde-atic",
    subname: "",
    description: "",
    details: { color: "Verde" },
    subcategories: ["gorros"],
    project: "atic",
    images_url: ["atic-gorro-m2-verde.png"],
    orders: [],
    price: 320,
    cost: 180,
    stock: 5,
    providers: [],
  },
  {
    name: "Gorro Clásic Amarillo",
    slug: "gorro-m1-amarillo-atic",
    subname: "",
    description: "",
    details: { color: "Amarillo" },
    subcategories: ["gorros"],
    project: "atic",
    images_url: ["atic-gorro-m1-amarillo.png"],
    orders: [],
    price: 320,
    cost: 180,
    stock: 5,
    providers: [],
  },
  {
    name: "Remera Hand",
    slug: "remera-m-hand-negra-atic",
    subname: "",
    description: "",
    details: { color: "Negro" },
    subcategories: ["remeras"],
    project: "atic",
    images_url: ["atic-remera-hand-negra-1.png"],
    orders: [],
    price: 580,
    cost: 320,
    stock: 10,
    providers: [],
  },
  {
    name: "Remera Snake",
    slug: "remera-m-snake-negra-atic",
    subname: "",
    description: "",
    details: { color: "Negro" },
    subcategories: ["remeras"],
    project: "atic",
    images_url: ["atic-remera-snake-negra-1.jpg"],
    orders: [],
    price: 580,
    cost: 320,
    stock: 10,
    providers: [],
  },
  {
    name: "Remera Skull",
    slug: "remera-m-skull-negra-atic",
    subname: "",
    description: "",
    details: { color: "Negro" },
    subcategories: ["remeras"],
    project: "atic",
    images_url: ["atic-remera-skull-negra-1.jpg"],
    orders: [],
    price: 580,
    cost: 320,
    stock: 10,
    providers: [],
  },
  {
    name: "Buzo Skull",
    slug: "buzo-m-skull-negro-atic",
    subname: "",
    description: "",
    details: { color: "Negro" },
    subcategories: ["buzos"],
    project: "atic",
    images_url: ["atic-buzo-skull-negro-1.png"],
    orders: [],
    price: 1200,
    cost: 700,
    stock: 5,
    providers: [],
  },
  {
    name: "Buzo Hand",
    slug: "buzo-m-hand-negro-atic",
    subname: "",
    description: "",
    details: { color: "Negro" },
    subcategories: ["buzos"],
    project: "atic",
    images_url: ["atic-buzo-hand-negro-1.png"],
    orders: [],
    price: 1200,
    cost: 700,
    stock: 5,
    providers: [],
  },
  {
    name: "Buzo Snake",
    slug: "buzo-m-snake-negro-atic",
    subname: "",
    description: "",
    details: { color: "Negro" },
    subcategories: ["buzos"],
    project: "atic",
    images_url: ["atic-buzo-snake-negro-1.png"],
    orders: [],
    price: 1200,
    cost: 700,
    stock: 5,
    providers: [],
  },
  {
    name: "Billetera Automática M.1 Black",
    slug: "billetera-automatica-negra-1.png",
    subname: "",
    description: "",
    details: { color: "Negro" },
    subcategories: ["billeteras"],
    project: "tero_ventas",
    images_url: ["teroventas-billetera-automatica-m1-negra-1.png"],
    orders: [],
    price: 1095,
    cost: 500,
    stock: 3,
    providers: [],
  },
  {
    name: "Billetera Automática M.1 Grey",
    slug: "billetera-automatica-gris-1.png",
    subname: "",
    description: "",
    details: { color: "Negro" },
    subcategories: ["billeteras"],
    project: "tero_ventas",
    images_url: ["teroventas-billetera-automatica-m1-gris-1.png"],
    orders: [],
    price: 1095,
    cost: 500,
    stock: 2,
    providers: [],
  },
  {
    name: "Billetera Automática M.1 Brown",
    slug: "billetera-automatica-brown-1.png",
    subname: "",
    description: "",
    details: { color: "Marrón" },
    subcategories: ["billeteras"],
    project: "tero_ventas",
    images_url: ["teroventas-billetera-automatica-m1-marron-1.png"],
    orders: [],
    price: 1095,
    cost: 500,
    stock: 2,
    providers: [],
  },
];

module.exports = defaultProducts;
