const defaultProjects = [
  /*     Atic */
  {
    name: "Atic",
    slug: "atic",
    members: ["magguer", "iviza"],
    roles: [],
    heading: "ropa-accesorios",
    color_one: "#b6b6b6",
    color_two: "#3b3b3b",
    logo_url: "logo_atic.png",
    banner_url: "atic-banner-1.png",
    needs: [],
    ubication: "",
    projects_fav: [],
    public: true,
    provider: false,
    networks: {
      fb: "",
      ig: "http://instagram.com/atic_uy",
      ln: "",
    },
    cateories: [],
    sub_cateories: [],
    products_on: true,
    services_on: false,
    products: [],
    services: [],
    users_client: [],
    projects_client: [],
    orders: [],
    bookings: [],
    invested_money: 0,
    sales_money: 0,
    spent_money: 0,
    banned: false,
  },
  /*     CuartoExpreso */
  {
    name: "CuartoExpreso",
    slug: "cuartoexpreso",
    members: ["magguer"],
    roles: [],
    heading: "produccion-musical",
    color_one: "#c52467",
    color_two: "#3d68df",
    logo_url: "logo_cuartoexpreso.png",
    banner_url: "cuartoexpreso-banner-1.png",
    needs: [],
    ubication: "",
    projects_fav: [],
    public: true,
    provider: false,
    networks: {
      fb: "",
      ig: "http://instagram.com/cuartoexpreso_",
      ln: "",
    },
    cateories: [],
    sub_cateories: [],
    products_on: false,
    services_on: true,
    products: [],
    services: [],
    users_client: [],
    projects_client: [],
    orders: [],
    bookings: [],
    invested_money: 0,
    sales_money: 0,
    spent_money: 0,
    banned: false,
  },
  /*     Noboss */
  {
    name: "Noboss",
    slug: "noboss",
    members: ["magguer"],
    roles: [],
    heading: "desarrollo-web-app",
    color_one: "#02997d",
    color_two: "#c9c9c9",
    logo_url: "logo_noboss.png",
    banner_url: "noboss-banner-1.jpg",
    needs: [],
    ubication: "",
    projects_fav: [],
    public: true,
    provider: false,
    networks: {
      fb: "",
      ig: "http://instagram.com/noboss.app",
      ln: "",
    },
    products_on: false,
    services_on: true,
    products: [],
    services: [],
    users_client: [],
    projects_client: [],
    orders: [],
    bookings: [],
    invested_money: 0,
    sales_money: 0,
    spent_money: 0,
    banned: false,
  },
  /*     TeroVentas */
  {
    name: "Tero Ventas",
    slug: "tero_ventas",
    members: ["magguer", "iviza"],
    roles: [],
    heading: "venta-variedad",
    color_one: "#e0e0e0",
    color_two: "#0c0c0c",
    logo_url: "logo_teroventas.png",
    banner_url: "",
    needs: [],
    ubication: "",
    projects_fav: [],
    public: true,
    provider: false,
    networks: {
      fb: "",
      ig: "http://instagram.com/teroventas.uy",
      ln: "",
    },
    cateories: [],
    sub_cateories: [],
    products_on: true,
    services_on: false,
    products: [],
    services: [],
    users_client: [],
    projects_client: [],
    orders: [],
    bookings: [],
    invested_money: 0,
    sales_money: 0,
    spent_money: 0,
    banned: false,
  },
  /*     Nohelia Iguines Personal Trainer */
  {
    name: "Nohelia Iguines - Personal Triner",
    slug: "noheliaiguines_personaltrainer",
    members: ["noheiguines"],
    roles: [],
    heading: "gym-personal-training",
    color_one: "#0c0c0c",
    color_two: "#e0e0e0",
    logo_url: "logo_niguinesptrainer.png",
    banner_url: "niguinesptrainer-banner-1.jpg",
    needs: [],
    ubication: "",
    projects_fav: [],
    public: true,
    provider: false,
    networks: {
      fb: "",
      ig: "http://instagram.com/niguines.personaltrainer",
      ln: "",
    },
    products_on: false,
    services_on: true,
    products: [],
    services: [],
    users_client: [],
    projects_client: [],
    orders: [],
    bookings: [],
    invested_money: 0,
    sales_money: 0,
    spent_money: 0,
    banned: false,
  },
];

module.exports = defaultProjects;
